import type { Metadata } from 'next'
import { Nunito, PT_Sans } from 'next/font/google'
import { PassportProvider } from '@/components/Passport'
import WalletProvider from '@/components/Wallet'
import './globals.css'

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
})

const ptSans = PT_Sans({
  variable: '--font-pt-sans',
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="zh-CN">
      <body className={`${nunito.variable} ${ptSans.variable} antialiased relative`}>
        <WalletProvider>
          <PassportProvider>{children}</PassportProvider>
        </WalletProvider>
      </body>
    </html>
  )
}
