import type { Metadata } from 'next'
import { Nunito, PT_Sans } from 'next/font/google'
import './globals.css'
import Navbar from '../components/Navbar'
import RightSidebar from '../components/RightSidebar'

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
})

const ptSans = PT_Sans({
  variable: '--font-pt-sans',
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="zh-CN">
      <body className={`${nunito.variable} ${ptSans.variable} antialiased relative`}>
        <Navbar />
        <div className="max-w-7xl mx-auto flex gap-8 mt-8">
          <div className="texture" />
          <div className="flex-1">{children}</div>
          <RightSidebar />
        </div>
      </body>
    </html>
  )
}
