/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BossFi Backend API
 * BossFi区块链后端API服务，支持钱包登录、用户管理、区块链数据同步等功能
 * OpenAPI spec version: 1.0.0
 */
import type { DtoCategoryInfo } from './dtoCategoryInfo';
import type { DtoUserInfo } from './dtoUserInfo';

/**
 * 文章的基本信息
 */
export interface DtoArticleInfo {
  /** 分类信息 */
  category?: DtoCategoryInfo;
  /** 分类ID */
  category_id?: number;
  /** 评论数 */
  comment_count?: number;
  /** 文章内容（截取前100字符） */
  content?: string;
  /** 创建时间 */
  created_at?: string;
  /** 文章ID */
  id?: number;
  /** 点赞数 */
  like_count?: number;
  /** 文章标题 */
  title?: string;
  /** 关联数据 */
  user?: DtoUserInfo;
  /** 浏览数 */
  view_count?: number;
}
