/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BossFi Backend API
 * BossFi区块链后端API服务，支持钱包登录、用户管理、区块链数据同步等功能
 * OpenAPI spec version: 1.0.0
 */
import type { DtoUserInfo } from './dtoUserInfo';

/**
 * 父评论的基本信息
 */
export interface DtoCommentInfo {
  /** 评论内容（截取前50字符） */
  content?: string;
  /** 创建时间 */
  created_at?: string;
  /** 评论ID */
  id?: number;
  /** 点赞数 */
  like_count?: number;
  /** 关联数据 */
  user?: DtoUserInfo;
}
