/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BossFi Backend API
 * BossFi区块链后端API服务，支持钱包登录、用户管理、区块链数据同步等功能
 * OpenAPI spec version: 1.0.0
 */
import type { DtoUserInfo } from './dtoUserInfo';

/**
 * 评论的响应数据结构
 */
export interface DtoCommentResponse {
  /** 文章ID */
  article_id?: number;
  /** 评论内容 */
  content?: string;
  /** 创建时间 */
  created_at?: string;
  /** 评论ID */
  id?: number;
  /** 是否已删除 */
  is_deleted?: boolean;
  /** 点赞数 */
  like_count?: number;
  /** 父评论ID */
  parent_id?: number;
  /** 回复列表 */
  replies?: DtoCommentResponse[];
  /** 关联数据 */
  user?: DtoUserInfo;
  /** 用户ID */
  user_id?: number;
}
