/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BossFi Backend API
 * BossFi区块链后端API服务，支持钱包登录、用户管理、区块链数据同步等功能
 * OpenAPI spec version: 1.0.0
 */
import type { DtoUserCommentResponse } from './dtoUserCommentResponse';

/**
 * 用户评论列表的响应数据结构
 */
export interface DtoUserCommentListResponse {
  /** 用户评论列表 */
  comments?: DtoUserCommentResponse[];
  /** 当前页码 */
  page?: number;
  /** 每页数量 */
  page_size?: number;
  /** 总评论数 */
  total?: number;
}
