/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BossFi Backend API
 * BossFi区块链后端API服务，支持钱包登录、用户管理、区块链数据同步等功能
 * OpenAPI spec version: 1.0.0
 */
import type { DtoArticleInfo } from './dtoArticleInfo';
import type { DtoCommentInfo } from './dtoCommentInfo';
import type { DtoUserInfo } from './dtoUserInfo';

/**
 * 用户评论的响应数据结构，包含完整的文章和父评论信息
 */
export interface DtoUserCommentResponse {
  /** 文章信息 */
  article?: DtoArticleInfo;
  /** 文章ID */
  article_id?: number;
  /** 评论内容 */
  content?: string;
  /** 创建时间 */
  created_at?: string;
  /** 评论ID */
  id?: number;
  /** 是否已删除 */
  is_deleted?: boolean;
  /** 点赞数 */
  like_count?: number;
  /** 父评论信息（如果存在） */
  parent?: DtoCommentInfo;
  /** 父评论ID */
  parent_id?: number;
  /** 关联数据 */
  user?: DtoUserInfo;
  /** 用户ID */
  user_id?: number;
}
