/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BossFi Backend API
 * BossFi区块链后端API服务，支持钱包登录、用户管理、区块链数据同步等功能
 * OpenAPI spec version: 1.0.0
 */

export interface DtoUpdateCategoryRequest {
  /** @maxLength 7 */
  color?: string;
  /** @maxLength 200 */
  description?: string;
  /** @maxLength 100 */
  icon?: string;
  is_active?: boolean;
  /** @maxLength 50 */
  name: string;
  sort_order?: number;
}
