/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BossFi Backend API
 * BossFi区块链后端API服务，支持钱包登录、用户管理、区块链数据同步等功能
 * OpenAPI spec version: 1.0.0
 */

export type GetArticlesSortOrder = typeof GetArticlesSortOrder[keyof typeof GetArticlesSortOrder];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetArticlesSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
