/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BossFi Backend API
 * BossFi区块链后端API服务，支持钱包登录、用户管理、区块链数据同步等功能
 * OpenAPI spec version: 1.0.0
 */

export type GetArticlesSortBy = typeof GetArticlesSortBy[keyof typeof GetArticlesSortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetArticlesSortBy = {
  created_at: 'created_at',
  like_count: 'like_count',
  view_count: 'view_count',
} as const;
