/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * BossFi Backend API
 * BossFi区块链后端API服务，支持钱包登录、用户管理、区块链数据同步等功能
 * OpenAPI spec version: 1.0.0
 */
import type { GetArticlesSortBy } from './getArticlesSortBy';
import type { GetArticlesSortOrder } from './getArticlesSortOrder';

export type GetArticlesParams = {
/**
 * 页码
 */
page?: number;
/**
 * 每页数量
 */
page_size?: number;
/**
 * 排序字段
 */
sort_by?: GetArticlesSortBy;
/**
 * 排序方向
 */
sort_order?: GetArticlesSortOrder;
/**
 * 用户ID
 */
user_id?: number;
/**
 * 分类ID
 */
category_id?: number;
/**
 * 关键字搜索
 */
keyword?: string;
};
